"""Author-only generation. Synthetic history is frozen after this run, not regenerated by agents."""
import json
import numpy as np
from build_inputs import build, PUBLIC, BASE
from reference import Model, BITS

def main():
    c = build()
    model = Model(c)
    rng = np.random.default_rng(20260925)
    m = 4
    records, latent, rejects = [], [], 0
    for number in range(6):
        n = 6 if number == 5 else 5
        while True:
            state = rng.choice(32, p=model.initial(m))
            years, states = [], []
            for t in range(n):
                if t:
                    state = rng.choice(32, p=model.T(m, 0, c['historical_hydrology'])[state])
                states.append(int(state))
                # Generate each visit from its fully enumerated probability, water once separately.
                visits = []
                for visit in range(2):
                    probs = np.array([model.emission(m, [BITS[o].tolist()])[state] for o in range(16)])
                    y = BITS[rng.choice(16, p=probs)].tolist()
                    if t >= 2 and rng.random() < .35:
                        y[int(rng.integers(4))] = None
                    visits.append(y)
                water = int(rng.random() < c['water_report_dry_probability'][state//16])
                if t >= 2 and rng.random() < .15:
                    water = None
                years.append({'visits': visits, 'water': water})
            if any(v == 1 for year in years[:2] for visit in year['visits'] for v in visit):
                break
            rejects += 1
        rid = 'focal' if number == 5 else f'archive-{number+1}'
        records.append({'id': rid, 'years': years})
        latent.append({'id': rid, 'states': states})
    (PUBLIC/'archive.json').write_text(json.dumps({'focal_id': 'focal', 'records': records}, indent=2)+'\n')
    (BASE/'author/generation_record.json').write_text(json.dumps({'seed': 20260925, 'hypothesis': 'M4',
                                                               'rejected': rejects, 'latent': latent}, indent=2)+'\n')
    print('Wrote six original synthetic records; author-only latent states kept outside public/.')

if __name__ == '__main__':
    main()
