#!/usr/bin/env python3
"""Regenerate task_list.md from the tasks tree.

The index is generated, never hand-edited, so it cannot drift from what is
actually on disk. Run it after creating, validating, packaging or submitting a
task; `tools/new-task.sh` and `tools/package.sh` call it themselves.

    tools/task-list.py            # rewrite task_list.md
    tools/task-list.py --check    # exit 1 if the file is stale (for CI/hooks)

Each task directory carries a `task-meta.json` holding the repo-side facts the
platform bundle has no place for: creation timestamp, status, one-line summary,
and the agent failure mode it targets. That file is excluded from the
submission zip by tools/package.sh.
"""

from __future__ import annotations

import argparse
import json
import sys
import tomllib
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TASKS = ROOT / "tasks"
INDEX = ROOT / "task_list.md"

# Ordered: a task moves down this list, never up.
STATUSES = ("building", "validated", "packaged", "submitted", "approved", "rejected")

STATUS_LABEL = {
    "building": "Building",
    "validated": "Validated",
    "packaged": "Packaged",
    "submitted": "Submitted",
    "approved": "Approved",
    "rejected": "Rejected",
}


@dataclass
class Task:
    slug: str
    date_dir: str
    created: str
    status: str
    completed: str | None
    summary: str
    failure_mode: str
    field: str
    subfield: str
    hours: float | None
    path: Path

    @property
    def sort_key(self) -> str:
        # Created timestamp orders the table; the date folder is the tiebreak
        # for tasks with no recorded time.
        return f"{self.created or self.date_dir}|{self.slug}"


def read_meta(task_dir: Path) -> dict:
    meta_path = task_dir / "task-meta.json"
    if not meta_path.is_file():
        return {}
    try:
        return json.loads(meta_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}


def read_toml(task_dir: Path) -> dict:
    toml_path = task_dir / "task.toml"
    if not toml_path.is_file():
        return {}
    try:
        return tomllib.loads(toml_path.read_text(encoding="utf-8"))
    except (OSError, tomllib.TOMLDecodeError):
        return {}


def unset(value: str) -> bool:
    return not value or str(value).startswith(("TODO", "UNSET"))


def discover() -> list[Task]:
    if not TASKS.is_dir():
        return []

    found: list[Task] = []
    # tasks/<YYYY-MM-DD>/<slug>/ is the layout; a bare tasks/<slug>/ from
    # before the dated layout is still picked up rather than silently dropped.
    for toml_path in sorted(TASKS.glob("*/*/task.toml")) + sorted(
        TASKS.glob("*/task.toml")
    ):
        task_dir = toml_path.parent
        parent = task_dir.parent
        date_dir = parent.name if parent != TASKS else "(undated)"

        meta = read_meta(task_dir)
        cfg = read_toml(task_dir)
        md = cfg.get("metadata", {})

        field = str(md.get("field", ""))
        subfield = str(md.get("subfield", ""))
        hours = md.get("expert_time_estimate_hours")

        found.append(
            Task(
                slug=task_dir.name,
                date_dir=date_dir,
                created=str(meta.get("created", "")),
                status=str(meta.get("status", "building")),
                completed=meta.get("completed"),
                summary=str(meta.get("summary", "")),
                failure_mode=str(meta.get("failure_mode", "")),
                field="—" if unset(field) else field,
                subfield="—" if unset(subfield) else subfield,
                hours=hours if isinstance(hours, (int, float)) and hours else None,
                path=task_dir,
            )
        )

    found.sort(key=lambda t: t.sort_key)
    return found


def cell(text: str, dash: str = "—") -> str:
    """Table-safe cell: no pipes, no newlines, never empty."""
    clean = " ".join(str(text).split()).replace("|", "/")
    return clean if clean else dash


def fmt_created(task: Task) -> str:
    if not task.created:
        return task.date_dir
    try:
        dt = datetime.fromisoformat(task.created.replace("Z", "+00:00"))
        return dt.strftime("%Y-%m-%d %H:%M")
    except ValueError:
        return task.created


def render(tasks: list[Task]) -> str:
    generated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    out: list[str] = [
        "# Task list",
        "",
        "Every task authored in this repository, oldest first by creation time.",
        "",
        "**Generated by `tools/task-list.py` — do not edit by hand.** Run that "
        "script after any change to a task; it rewrites this file from the "
        "contents of `tasks/`.",
        "",
    ]

    if not tasks:
        out += [
            "_No tasks yet._",
            "",
            "Create one with `tools/new-task.sh <slug>`. It lands in "
            "`tasks/<YYYY-MM-DD>/<slug>/` and appears here automatically.",
            "",
            "---",
            "",
            f"<sub>Generated {generated}</sub>",
            "",
        ]
        return "\n".join(out)

    # Summary counts, so the state of play is readable without the table.
    by_status = {s: 0 for s in STATUSES}
    for t in tasks:
        by_status[t.status] = by_status.get(t.status, 0) + 1
    live = [f"{STATUS_LABEL.get(s, s)} {n}" for s, n in by_status.items() if n]

    by_field: dict[str, int] = {}
    for t in tasks:
        if t.field != "—":
            by_field[t.field] = by_field.get(t.field, 0) + 1

    out += [
        f"**{len(tasks)} task{'s' if len(tasks) != 1 else ''}** · "
        + " · ".join(live),
        "",
    ]
    if by_field:
        out += [
            "**By field:** "
            + " · ".join(f"{f} {n}" for f, n in sorted(by_field.items())),
            "",
        ]

    out += [
        "| # | Created | Task | Field | Subfield | Status | Targeted failure mode | Est. hours |",
        "| ---: | --- | --- | --- | --- | --- | --- | ---: |",
    ]

    for i, t in enumerate(tasks, 1):
        rel = t.path.relative_to(ROOT)
        link = f"[`{t.slug}`]({rel}/)"
        status = STATUS_LABEL.get(t.status, t.status)
        if t.completed:
            status = f"{status} · {cell(t.completed)}"
        out.append(
            f"| {i} | {fmt_created(t)} | {link} | {cell(t.field)} | "
            f"{cell(t.subfield)} | {status} | {cell(t.failure_mode)} | "
            f"{t.hours if t.hours else '—'} |"
        )

    out += ["", "## Summaries", ""]
    for t in tasks:
        rel = t.path.relative_to(ROOT)
        out.append(f"### `{t.slug}`")
        out.append("")
        out.append(f"- **Location:** `{rel}/`")
        out.append(f"- **Created:** {fmt_created(t)}")
        out.append(f"- **Status:** {STATUS_LABEL.get(t.status, t.status)}")
        if t.completed:
            out.append(f"- **Completed:** {cell(t.completed)}")
        out.append(f"- **Field:** {cell(t.field)} / {cell(t.subfield)}")
        out.append(f"- **Failure mode:** {cell(t.failure_mode)}")
        if t.summary:
            out += ["", cell(t.summary)]
        out.append("")

    out += ["---", "", f"<sub>Generated {generated}</sub>", ""]
    return "\n".join(out)


def strip_stamp(text: str) -> str:
    """Drop the generated-at line so --check compares content, not clock."""
    return "\n".join(
        ln for ln in text.splitlines() if not ln.startswith("<sub>Generated ")
    )


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if task_list.md is out of date, writing nothing")
    args = ap.parse_args()

    rendered = render(discover())

    if args.check:
        current = INDEX.read_text(encoding="utf-8") if INDEX.is_file() else ""
        if strip_stamp(current) != strip_stamp(rendered):
            print("task_list.md is out of date; run tools/task-list.py",
                  file=sys.stderr)
            return 1
        print("task_list.md is up to date")
        return 0

    INDEX.write_text(rendered, encoding="utf-8")
    print(f"wrote {INDEX.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
